### ISSUE TITLE
cardano.enable() throws an exception when the connection is not accepted

### ISSUE THREAD

**Issue by eddex** [Berry-Pool/nami-wallet#144] opened 2021-12-18 11:07 UTC
**Description**
When the [cardano.enable()](https://github.com/Berry-Pool/nami-wallet/blob/400637882f08b2efc9299396d37eff76934ab3ea/src/api/webpage/index.js#L9) method is called from JavaScript, there are 2 possible scenarios.

1. The user accepts the connection
2. The user cancels the connection or closes the pop-up window

In the first case, the promise is resolved and returns `true`. But in the second case, an exception is thrown and the execution of the method is interrupted. The promise never returns anything.

**Steps to reproduce**
1. Run `await cardano.enable()` in the browser console
2. Close the nami popup window

**Expected behavior**
The promise returned by `await cardano.enable()` resolves and returns `false`.

**Actual behavior**
An exception is thrown with the message: `The request was refused due to lack of access - e.g. wallet disconnects`.
The promise is not resolved.

**About**
Nami version: 3.0.0
Browser: Chrome

> Edit: I do realize that the current behavior is according to the specifications in the README, but it is very counter intuitive. Throwing exceptions should be avoided if possible.

**Comment by alessandrokonrad** [comment] 2021-12-18 17:52
The `cardano.enable()` function works correct. Returning `false` would not be correct. The promise is resolved in both cases, however in one it throws an error. If you simply want to ignore it, you can catch the error and do nothing with it.

**Comment by eddex** [comment] 2021-12-19 15:34
> Returning false would not be correct.

Why not? Using exceptions to control program flow is not a good practice imo. Besides that it's not consistent with `cardano.isEnabled()` which returns `false` if the wallet is not connected.

**Comment by pascallapointe** [comment] 2021-12-20 12:06
You can't compare both method. cardano.isEnabled()  is a boolean method, it will return true or false by design. It could also throw an exception due to internal failure. In the case of cardano.enable(), the expected result is always a successful connection. Returning only false on failure would bypass the actual cause of the failure and you would be clueless about what is causing the failure.
I disagree that Exception control is a bad practice, on the other side, silent failure would be a bad practice.

**Closed** 2022-01-09 12:13 UTC
